export const VDOMType = Object.freeze({
  TEXT: "TEXT",
  ELEMENT: "ELEMENT",
  COMPONENT: "COMPONENT",
  RAW_HTML: "RAW_HTML",
  FRAGMENT: "FRAGMENT",
  OBSERVABLE: "OBSERVABLE",
  SUSPENSE: "SUSPENSE",
  CHILDREN: "CHILDREN",
  NULL: "NULL",
})
